### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VasekTryba4eB** [remix30303/SlaveHack2_cheat#1]
Not working... something going wrong. Help plz

`Traceback (most recent call last):
  File "bot_SL2.py", line 16, in <module>
    browser = webdriver.Chrome("/home/butcher/Downloads/SlaveHack2_cheat-master/chromedriver",chrome_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
`

**Comment by ChrisGSA** [comment]
First, make sure to **update** your chrome driver by downloading the latest version [here](https://sites.google.com/a/chromium.org/chromedriver/downloads).

Next, you have to make sure your **Directory** is _correct_. If you want to check for this drag your **chromedriver.exe** file into CMD and copy the directory it gives you into the designated area in bot_SL2.py
Hope this helps!

**Comment by k1epto** [comment]
I modified it to work in Linux (i think, partially untested) .... file:///home/bipolarmorgan/linux_bot_SL2.py.txt

You have to change `chrome_options=options` to `options=options` for one ... and the next thing you'll have to change is what it looks for once it logs in... `element_present = EC.presence_of_element_located((By.ID, 'icon-logout'))`
